name: CI - Playwright Tests (Allure)

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

concurrency:
  group: ci-playwright-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      # Install allure-playwright reporter and allure CLI locally (no package.json change)
      - name: Install Allure reporter + CLI
        run: npm install --no-save allure-playwright allure-commandline@2.13.9

      - name: Install Playwright browsers (with deps)
        run: npx playwright install --with-deps

      - name: Run Playwright tests (generate Allure results)
        run: |
          # ensure results dir is clean
          rm -rf allure-results
          mkdir -p allure-results
          # run tests and emit allure results
          npx playwright test --reporter=list --reporter=allure-playwright
        env:
          CI: true

      # Always attempt to generate the Allure HTML report (so artifacts exist for debugging)
      - name: Generate Allure report
        if: always()
        run: |
          # generate HTML from allure-results --> allure-report
          npx allure generate allure-results -o allure-report --clean || echo "Allure generate failed or no results"

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload test-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results