name: CI - Playwright Tests (Allure -> GitHub Pages)

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

concurrency:
  group: ci-playwright-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Playwright tests and publish Allure report
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Install Playwright browsers (with deps)
        run: npx playwright install --with-deps

      - name: Run Playwright (Allure results)
        env:
          CI: true
          ALLURE_RESULTS_DIR: .run/reports/allure/results
        run: |
          rm -rf .run/reports/allure
          mkdir -p .run/reports/allure/results
          npx playwright test --reporter=list --reporter=allure-playwright

      - name: Generate Allure HTML report
        if: always()
        run: |
          npx allure generate .run/reports/allure/results -o .run/reports/allure/report --clean || echo "no allure results"

      - name: List generated report files (debug)
        if: always()
        run: |
          echo "Allure results folder:"
          ls -la .run/reports/allure/results || true
          echo "Allure report folder:"
          ls -la .run/reports/allure/report || true

      - name: Check Allure report exists
        id: check_report
        if: always()
        run: |
          if [ -d ".run/reports/allure/report" ] && [ "$(ls -A .run/reports/allure/report)" ]; then
            echo "report_exists=true" >> $GITHUB_OUTPUT
          else
            echo "report_exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Upload Allure artifact (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: .run/reports/allure

      - name: Deploy Allure HTML to GitHub Pages (gh-pages)
        if: steps.check_report.outputs.report_exists == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .run/reports/allure/report
          publish_branch: gh-pages
          keep_files: false

      - name: Report status (optional)
        if: always()
        run: echo "Allure report deployed (if available) to gh-pages branch"
