name: CI - Playwright Tests (Allure)

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

concurrency:
  group: ci-playwright-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (Using Node 20 LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Updated to the current LTS version for better stability
          cache: 'npm'

      - name: Install dependencies (Playwright, Allure Reporter, Allure CLI)
        # CRITICAL FIX: Assumes 'allure-playwright' and 'allure-commandline' are in package.json.
        # 'npm ci' installs them reliably, eliminating the separate, fragile 'npm install --no-save' step.
        run: npm ci
        env:
          CI: true

      - name: Install Playwright browsers (with deps)
        run: npx playwright install --with-deps

      - name: Run Playwright tests (generate Allure results)
        run: |
          # Clean up and ensure results dir exists
          rm -rf allure-results allure-report playwright-report test-results
          mkdir -p allure-results
          # Run tests and emit allure results
          npx playwright test --reporter=list,allure-playwright
        env:
          CI: true

      # Always attempt to generate the Allure HTML report (for artifact upload)
      - name: Generate Allure report
        if: always()
        run: |
          # Generate HTML from allure-results --> allure-report
          npx allure generate allure-results -o allure-report --clean || echo "Allure generate failed or no results"

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-raw # Renamed for clarity vs. HTML report
          path: allure-results

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload test-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
